export { default as Home } from './Home'
export { default as Catalog } from './Catalog'
export { default as Favorits } from './Favorits'
export { default as Profile } from './Profile'
export { default as Cart } from './Cart'